version: '3.7'
services:
  hadoop:
    image: sequenceiq/hadoop-docker:2.7.0
    ports: 
      - "50700:50700"
      - "9000:9000"
      - "50010:50010"

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: some_pass
      POSTGRES_DB: vacancies_db
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  data_fetcher:
    build: ./fetcher
    depends_on: 
      - hadoop

  data_extractor:
    build: ./extractor
    depends_on: 
      - hadoop
      - data_fetcher 
      - postgres

networks:  
  hadoop_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16 

